title: 정주희의 포트폴리오
name: 정주희
email: jieboong82@gmail.com
description: >-
  Backend Developer


baseurl: ""
url: "https://jieboong.github.io/"


# profile 이미지
profile_image: images/mypic_1.png


# Youtube vid
youtube_vid: #


# Custom Color
primary: 9AD941 #2c98f0 #b72cf0
primary_hover: D2AAFA #44A4F2 #9a2dc7
color_1: bde0fe
color_2: cdb4db
color_3: ffafcc
color_4: a2d2ff
color_5: ffc8dd
color_6: b9fbc0


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/mypic_4.png
  title: Jung Ju Hee's <br>Portfolio
  positioin: absolute
  transforms: translate(-50%, -50%)
  left: -10px
  bottom: 0px
  float: middle


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/mypic_5.png
  title: BE Developer
  positioin: absolute
  transforms: translate(-50%, -50%)
  left: 150px
  bottom: 0px   
  float: middle


#ㄹ About
about_meta: About Me
about_header: >- 
  "인생은 실전"
about_introduce: >-
  "안녕하세요. 백엔드 개발자가 되고 싶은 대학생 정주희입니다."
about_content: >-
    단순히 컴퓨터 이것저것 만지기를 좋아해 컴퓨터공학과에 진학했습니다.<br>
    코딩의 c도 모르고 진학한 대학교에서 코딩이 익숙해지기까지 4년이 걸렸습니다.<br>

    내가 앞으로 개발자라는 필드에서 몸담으려면 어떤 개발자가 되고 싶나라는 고민을 한 결과, 사람들 사이에 쓰이는 서비스를 만드는 개발자가 되고 싶다는 결론을 냈습니다. 그럼 가장 많이 쓰이는 웹서비스를 개발해보자라고 마음을 먹고 그 이후 서버 개발자가 되기 위해 스프링 공부를 시작했습니다. 스프링을 배운지 한 달도 되지 않아 멘땅에 헤딩으로 시작한 협업 프로젝트인 채팅 서비스 개발부터 시국에 맞는 서비스를 개발하기 위해 진행한 프로젝트인 코로나19 백신 플랫폼 개발까지 다양한 프로젝트에 도전하며 성장하고 있습니다.

    프로젝트를 진행하는 과정에서도 내가 어떻게 하면 더 잘할수있을까 끊임없이 고민하며 더 좋은 코드를 위해 공부를 해나가고 있습니다.

about_services: # 형식에 맞추어 항목 추가
- icon: icon-data
  name: Server
- icon: icon-monitor
  name: Web
- icon: icon-code
  name: Java
- icon: icon-code
  name: Python


# Tech  skill
tech_meta: My current skills
tech_header: TECH SKILLS
tech_content: content
tech_list: # 형식에 맞추어 항목 추가
- name: Java
  color: color-1
  animation: fadeInLeft
  percent: 50
  mark: 50
  content: 
- name: Spring Boot
  color: color-2
  animation: fadeInRight
  percent: 40
  mark: 40
  content: Rest api 개발에 익숙하고 JPA, Spring Security 등 다양한 라이브러리 활용 경험이 있습니다.
- name: Python
  color: color-3
  animation: fadeInLeft
  percent: 40
  mark: 40
  content: 파이썬 기초, 문법에 익숙하며 크롤링, 데이터 분석 등을 공부했습니다.
- name: Github
  color: color-4
  animation: fadeInRight
  percent: 40
  mark: 40
  content: feature 별로 브랜치를 관리할 수 있으며, Merge Request를 통해 협업 경험이 있습니다. 
tech_desc: 


# Project
project_meta: 프로젝트
project_header: My Projects
project_introduce: <span>개인 프로젝트</span><span>팀 프로젝트</span><span>Business</span>
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: https://github.com/jieboong

project_team_name: 팀프로젝트
project_team: # 형식에 맞추어 항목 추가
- background_url: images/khuvid.png
  animation: fadeInRight
  name: 코로나19 백신 후기 서비스 Khuvid19
  description: 코로나 19 백신을 태그형 후기로 작성 및 조회 할 수 있고, 자유게시판 및 코로나19에 대한 정보 확인 등을 제공하는 웹서비스입니다.캡스톤 디자인 프로젝트로 약 4개월간 스프린트 회의로 진행되었으며, 본 프로젝트에서 서버 개발자로 참여했습니다.
  detail_url: https://github.com/Khuvid19
  readmore_url: https://sprinkle-rodent-a50.notion.site/KHUVID-19-19-2a83d072c65e40c0b6549e9614058b07

- background_url: images/zamditbul.png
  animation: fadeInRight
  name: 잠딧불 프로젝트
  description: 사용자가 웹에서 자신의 무드등 설정을 할 수 있는 개발 프로젝트입니다. 약 3개월간 진행된 프로젝트로 본 프로젝트에 서버 개발자로 참여했습니다.
  detail_url: https://github.com/zamditbul/zamditbul-server
  readmore_url: https://sprinkle-rodent-a50.notion.site/D-c56d3760dcf4417599c1bd2ea83e54c5

- background_url: images/topgoal.png
  animation: fadeInRight
  name: 채팅 프로젝트
  description: T.G.Wing에서의 방학 해커톤 프로젝트로 진행된 프로젝트로, 웹과 앱에서 동시에 사용되는 채팅 프로젝트입니다. 이 프로젝트에서 서버 개발자로 참여했습니다.
  detail_url: https://github.com/TopGoal01/Server



# Experience
exp_meta: What have I achieved?
exp_header: 개발 
exp_content: 개발 능력 외에 역량
exp_services: # 형식에 맞추어 항목 추가
- name: 새로운 기술 학습
  color: color-1
  icon: icon-bulb
  content: 새로운 언어, 기술을 공부하는데 흥미가 있고 열성을 다합니다.
- name: 애자일 프로세스
  color: color-2
  icon: icon-phone3
  content: 스크럼 회의를 통해 피드백을 받고 개발 과정을 관리하는 것에 익숙합니다.
  



# Career
carerr_meta: Activity
carerr_header: 대외활동
carerr_content: 수업 이외의 장소에서 개발에 관심있는 사람들과 모여 이런 활동을 했습니다.
career_list:
- name: 경희대학교 학과동아리 T.G.Wing
  date: 2018.03 ~ 2022.08
  content: "운영진 활동(2019.03 ~ 2021.01)<br>OT, MT 및 주점 운영 등 친목 활동 기획<br>대면(2019) 및 비대면(2020) 새내기 교육 기획"
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
- name: 빅데이터 연합동아리 BOAZ
  date: 2021.08 ~ 2022.08
  content: "빅데이터 엔지니어링 17기 활동중<br>엔지니어링 멘토 활동(2022.01 ~ 2022.02)<br>OS스터디, 서버 케이스 스터디 참여"
  color: color-2
  icon: icon-pen2
  animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: KyungHee University Computer Engineering
  subtitle: 경희대학교 컴퓨터공학과 졸업 예정
  date: 2018.03 ~ 2022.08


# Blog
blog_meta: self-improvement
blog_header: BLOG
blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
blog_load_more_url: 
blog_list:
- title: 개발자가 되어볼게요
  subtitle: 개발 블로그 운영
  date: 2021.01
  content: 프로젝트를 진행해오면서 자주 발생하는 실수들을 기록하기 위해서 만든 공간입니다. 앞으로는 프로젝트를 진행하면서 기획과 그에 대한 생각들도 올릴 예정입니다.  
  thumbnail_url: images/blog_thumb.png
  link: https://jieboong.github.io/

#GitHub
github_title: Github
github_content: 현재까지 진행해온 프로젝트들과 혼자서 공부해온 코드들이 있는 공간입니다.
github_tuhmbnail: images/my_pic4.png
github_link: https://github.com/Jieboong

optional_front_matter:
  remove_originals:    true
